### ISSUE TITLE
Discuss the custom metacoder format.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/MicrobiomeR#38]
# Formatting Code
https://github.com/vallenderlab/MicrobiomeR/blob/fac9b427a6b461b57c4f6cfb23f4240774a0d59b/R/metacoder-formatting.R#L365-L401

# Format

```yaml
# The metacoder_obj$data will contain the following tables.
# The keys here are the old phyloseq table names, and the values are the new table names
...
otu_table: "otu_abundance"
tax_data: "otu_annotations"
sample_data: "sample_data"
phy_tree: "phy_tree"
...
# These new tables are created by metacoder's calculation functions
...
calc_taxon_abund(otu_abundance): "taxa_abundance"
calc_obs_props(otu_abundance): "otu_proportions"
calc_obs_props(otu_proportions): "taxa_proportions"
...
```

# Validation Code

These functions will be used to validate the data before filter with the new functions.

https://github.com/vallenderlab/MicrobiomeR/blob/fac9b427a6b461b57c4f6cfb23f4240774a0d59b/R/metacoder-formatting.R#L520-L561

# Validation types

You have 2 types of custom (MicrobiomeR style) metacoder objects.
* basic - An object that has been converted from phyloseq to metacoder to formatted metacoder, but has not had any calculations added to it

```r
format_metacodr_object(metacoder_object, abundance = FALSE, proportions = FALSE)
```

* analyzed - This object has had calculations added to it.

```r
format_metacodr_object(metacoder_object, abundance = TRUE, proportions = TRUE)
```

This functionality was added because some functions need to be used before analysis, other need to be used after analysis, and for some functions, it doesn't matter either way.  It also makes sure the data is being manipulated properly by forcing the format if desired.

There is also a function for validating an object if the format doesn't matter or if it is unknown.
