### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by sdhutchins** [vallenderlab/MicrobiomeR#60]
Use the [covr](https://github.com/r-lib/covr) package to add code coverage badge/stats to package.

- [x] Setup code coverage with usethis `usethis::use_coverage()`
- [x] Add code coverage badge
- [x] Add code coverage commands to `.travis.yml`

```yaml
r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
```
